
language: node_js

node_js:
  - 6.9.1
  - 8.12.0

before_install:
  - npm i -g npm@^6.0.0

env:
  - BUILD_STAGE=lint
  - BUILD_STAGE=test-unit
  - BUILD_STAGE=test-integration
  - BUILD_STAGE=test-npm-security

script:
  - npm run ${BUILD_STAGE}

notifications:
  email:
    on_success: change
    on_failure: always
